code M2L03
=====

In [1]:
import numpy as np
from numpy import dot, arange, array, sqrt, eye, diag, ones, tril, var, mean, matmul, cumprod, cumsum
from numpy.random import permutation
from numpy.linalg import norm

numpy cumprod and cumsum
==
These 2 functions are useful in a few scenarios, like in simulating asset price paths in Monte Carlo simulation. Proper use of them saves you from using loops and makes your intention more explicit.

https://numpy.org/doc/stable/reference/generated/numpy.cumprod.html

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [2]:
a = array([1,2,3])
print(cumprod(a) )
print()

b = array([[1, 2, 3], [4, 5, 6],[7,8,9]])
print(b)
print()
print(cumprod(b))
print()
print(cumprod(b,0))
print()
print(cumprod(b,1))

[1 2 6]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[     1      2      6     24    120    720   5040  40320 362880]

[[  1   2   3]
 [  4  10  18]
 [ 28  80 162]]

[[  1   2   6]
 [  4  20 120]
 [  7  56 504]]


In [3]:
a = array([1,2,3])
print(cumsum(a) )
print()

b = array([[1, 2, 3], [4, 5, 6],[7,8,9]])
print(b)
print()
print(cumsum(b))
print()
print(cumsum(b,0))
print()
print(cumsum(b,1))

[1 3 6]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[ 1  3  6 10 15 21 28 36 45]

[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]

[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


Code snippets for M2L03
==

Elimination with Matrices
-----

In [4]:
A = array([[1,2,1],[3,8,1],[0,4,1]])
print(A)
print()

E21 = array([[1,0,0],[-3,1,0],[0,0,1]])
print(E21)
print()

print(E21 @ A)

[[1 2 1]
 [3 8 1]
 [0 4 1]]

[[ 1  0  0]
 [-3  1  0]
 [ 0  0  1]]

[[ 1  2  1]
 [ 0  2 -2]
 [ 0  4  1]]


In [5]:
E32 = array([[1, 0 ,0],[0,1,0],[0,-2,1]])
print(E32)
print()

print(E32 @ E21 @ A)

[[ 1  0  0]
 [ 0  1  0]
 [ 0 -2  1]]

[[ 1  2  1]
 [ 0  2 -2]
 [ 0  0  5]]


In [6]:
print(E32 @ E21)

[[ 1  0  0]
 [-3  1  0]
 [ 6 -2  1]]


Inverse Matrices
--

In [7]:
print(E21)
print()

InvE21 = array([[1,0,0],[3,1,0],[0,0,1]])
print(InvE21)
print()

print(A)
print(E21@A)
print(InvE21@E21@A)

[[ 1  0  0]
 [-3  1  0]
 [ 0  0  1]]

[[1 0 0]
 [3 1 0]
 [0 0 1]]

[[1 2 1]
 [3 8 1]
 [0 4 1]]
[[ 1  2  1]
 [ 0  2 -2]
 [ 0  4  1]]
[[1 2 1]
 [3 8 1]
 [0 4 1]]
