Numpy Broadcasting
===

In [17]:
import numpy as np
from numpy import mod, arange, reshape, array, sum, cumprod

---
Example 1
===

In [5]:
A = np.array([[4, 7, 6, 5],
              [9, 2, 8, 7],
              [9, 1, 6, 1],]
            )
print(A)
print()

B = np.array([[7, 3, 1]]).T
print(B)
print()

print(A + B)

[[4 7 6 5]
 [9 2 8 7]
 [9 1 6 1]]

[[7]
 [3]
 [1]]

[[11 14 13 12]
 [12  5 11 10]
 [10  2  7  2]]


---
Example 2
===

In [6]:
A = np.array([[3, 9, 3, 2],
              [8, 6, 3, 5],
              [7, 1, 9, 7],
              [6, 4, 2, 2],]
            )
print(A)
print()

B = np.array([[7, 2]]).T
print(B)
print()

print(A + B)

[[3 9 3 2]
 [8 6 3 5]
 [7 1 9 7]
 [6 4 2 2]]

[[7]
 [2]]



ValueError: operands could not be broadcast together with shapes (4,4) (2,1) 

---
Example 3
===

In [14]:
x = np.arange(4)
print(x)
print()

y = np.ones(5)
print(y)
print()

print(x.shape)
print(y.shape)
print()

print(x + y)

[0 1 2 3]

[1. 1. 1. 1. 1.]

(4,)
(5,)



ValueError: operands could not be broadcast together with shapes (4,) (5,) 

---
Example 4
===

In [13]:
x = np.arange(4)
X = x.reshape(4, 1)
print(X)
print()

y = np.ones(5)
print(y)
print()

print(X.shape)
print(f'( , {y.shape[0]})')
print()

print(X + y)

[[0]
 [1]
 [2]
 [3]]

[1. 1. 1. 1. 1.]

(4, 1)
( , 5)

[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


---
Quiz
===

You pick a single number uniformly at random from the set {1, 2, 3, …, 1000}, i.e., the first 1000 positive integers. What is the probability that it’s a multiple of any two of the numbers 7, 11, or 13?

In [16]:
sum(sum(mod(arange(1,1001).reshape(1,-1),array([[7,11,13]]).T)==0,axis=0)==2)/1000

0.028

---
Quiz
===

A group of three friends are hanging out. Let’s assume their birthdays are uniformly and independently distributed across the 365-day year. The probability that some (i.e. at least two) of the people in this group have a birthday in common is as follows:

1-(365×364×363)/(365×365×365)≅0.0082

How the above expression comes about is simply 100% minus the probability that everyone in the group has a different birthday. Not surprisingly, the larger the group, the higher the probability of a birthday in common.
Using this setup, what is the smallest group size such that the probability of a birthday in common is larger than 50%?

In [18]:
sum(1 - cumprod(arange(365,0,-1.)/365) < .5) + 1

23